config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :gas_stations
  root to:'gas_stations#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/gas_station.rb
class GasStation < ApplicationRecord
  belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :gas_stations
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/gas_stations_controller.rb
class GasStationsController < ApplicationController
  before_action :set_gas_station, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!, except: [:index]
  # GET /gas_stations
  # GET /gas_stations.json
  def index
    @gas_stations = GasStation.all
  end

  # GET /gas_stations/1
  # GET /gas_stations/1.json
  def show
  end

  # GET /gas_stations/new
  def new
    @gas_station = GasStation.new
  end

  # GET /gas_stations/1/edit
  def edit
  end

  # POST /gas_stations
  # POST /gas_stations.json
  def create
    @gas_station = GasStation.new(gas_station_params)
    @gass_station.user = current_user
    respond_to do |format|
      if @gas_station.save
        format.html { redirect_to @gas_station, notice: 'Gas station was successfully created.' }
        format.json { render :show, status: :created, location: @gas_station }
      else
        format.html { render :new }
        format.json { render json: @gas_station.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /gas_stations/1
  # PATCH/PUT /gas_stations/1.json
  def update
    respond_to do |format|
      if @gas_station.update(gas_station_params)
        format.html { redirect_to @gas_station, notice: 'Gas station was successfully updated.' }
        format.json { render :show, status: :ok, location: @gas_station }
      else
        format.html { render :edit }
        format.json { render json: @gas_station.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /gas_stations/1
  # DELETE /gas_stations/1.json
  def destroy
    @gas_station.destroy
    respond_to do |format|
      format.html { redirect_to gas_stations_url, notice: 'Gas station was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_gas_station
      @gas_station = GasStation.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def gas_station_params
      params.require(:gas_station).permit(:address, :image, :name, :id_station)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/gas_stations_helper.rb
module GasStationsHelper
end

app/views/gas_stations/_form.html.erb
<%= form_with(model: gas_station, local: true) do |form| %>
  <% if gas_station.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(gas_station.errors.count, "error") %> prohibited this gas_station from being saved:</h2>

      <ul>
      <% gas_station.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :address %>
    <%= form.text_field :address, id: :gas_station_address %>
  </div>

  <div class="field">
    <%= form.label :image %>
    <%= form.text_field :image, id: :gas_station_image %>
  </div>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name, id: :gas_station_name %>
  </div>

  <div class="field">
    <%= form.label :id_station %>
    <%= form.number_field :id_station, id: :gas_station_id_station %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/gas_stations/edit.html.erb
<h1>Editing Gas Station</h1>

<%= render 'form', gas_station: @gas_station %>

<%= link_to 'Show', @gas_station %> |
<%= link_to 'Back', gas_stations_path %>

app/views/gas_stations/index.html.erb
<h1>Estaciones de servicio</h1>

<div class="row">
  <% @gas_stations.each do |gas_station| %>
   <div class="col-sm-6 col-md-4">
     <div class="thumbnail">
       <%= image_tag gas_station.image, class: 'img-responsive center-block', style:'max-height:300px;' %>
       <div class="caption">
         <h3>Nombre: <%= gas_station.name %></h3>
         <p>Dirección<%= gas_station.address %></p>
         <p>ID:<%= gas_station.id_station %></p>
         <p>Correo de Contacto: <%= gas_station.user.email if gas_station.user %></p>
         <p><%= link_to 'Detalles', gas_station, class: 'btn btn-primary' %>
         <%= link_to 'Editar', edit_gas_station_path(gas_station), class:'btn btn-warning' %>
         <%= link_to 'eliminar', gas_station, method: :delete, data: { confirm: 'Are you sure?' }, class: 'btn btn-danger' %></p>
       </div>
     </div>
   </div>
 <% end %>
</div>

<br>

<%= link_to 'New Gas Station', new_gas_station_path, class: "btn btn-success" %>

app/views/gas_stations/new.html.erb
<h1>New Gas Station</h1>

<%= render 'form', gas_station: @gas_station %>

<%= link_to 'Back', gas_stations_path %>

app/views/gas_stations/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Address:</strong>
  <%= @gas_station.address %>
</p>

<p>
  <strong>Image:</strong>
  <%= @gas_station.image %>
</p>

<p>
  <strong>Name:</strong>
  <%= @gas_station.name %>
</p>

<p>
  <strong>Id station:</strong>
  <%= @gas_station.id_station %>
</p>

<%= link_to 'Edit', edit_gas_station_path(@gas_station) %> |
<%= link_to 'Back', gas_stations_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <title>CopecApp</title>
    <%= csrf_meta_tags %>
    <!-- Latest compiled and minified CSS -->
<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/3.4.1/css/bootstrap.min.css" integrity="sha384-HSMxcRTRxnN+Bdg0JdbxYKrThecOKuH5zCYotlSAcp1+c8xmyTe9GYg1l9a69psu" crossorigin="anonymous">
<!-- Optional theme -->
<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/3.4.1/css/bootstrap-theme.min.css" integrity="sha384-6pzBo3FDv/PJ8r2KRkGHifhEocL+1X2rVCTTkUfGk7/0pbek5mMa1upzvWbrUbOZ" crossorigin="anonymous">
<script src="https://code.jquery.com/jquery-1.12.4.min.js" integrity="sha384-nvAa0+6Qg9clwYCGGPpDQLVpLNn0fRaROjHqs13t4Ggj3Ez50XnGQqc/r8MhnRDZ" crossorigin="anonymous"></script>
<!-- Latest compiled and minified JavaScript -->
<script src="https://stackpath.bootstrapcdn.com/bootstrap/3.4.1/js/bootstrap.min.js" integrity="sha384-aJ21OjlMXNL5UyIl/XNwTMqvzeRMZH2w8c5cRVpzpU8Y5bApTppSuUkhZXN0VxHd" crossorigin="anonymous"></script>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>
  <body>
    <nav class="navbar navbar-default">
       <div class="container-fluid">
         <!-- Brand and toggle get grouped for better mobile display -->
         <div class="navbar-header">
           <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
             <span class="sr-only">Toggle navigation</span>
             <span class="icon-bar"></span>
             <span class="icon-bar"></span>
             <span class="icon-bar"></span>
           </button>
           <a class="navbar-brand" href="./index.html">Tienda Copec</a>
         </div>

         <!-- Collect the nav links, forms, and other content for toggling -->
         <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
           <ul class="nav navbar-nav">
             <li class="active"><a href="./news.html">Novedades</a></li>
             <li><a href="./promos.html">Promociones</a></li>
             <li><a href="./contact.html">Contacto</a></li>
           </ul>
           <ul class="nav navbar-nav navbar-right">
             <li><%= link_to 'Ingresar', new_user_session_path unless user_signed_in?%></li>
             <li class="dropdown">
               <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Dropdown <span class="caret"></span></a>
               <ul class="dropdown-menu">
                 <li><a href="#">Action</a></li>
                 <li><a href="#">Another action</a></li>
                 <li><a href="#">Something else here</a></li>
                 <li role="separator" class="divider"></li>
                 <li><%= link_to 'Salir',destroy_user_session_path, method: :delete if user_signed_in?%></li>
               </ul>
             </li>
           </ul>
         </div><!-- /.navbar-collapse -->
       </div><!-- /.container-fluid -->
     </nav>
      <p class="notice"><%= notice %></p>
      <p class="alert"><%= alert %></p>
    <%= yield %>
  </body>
</html>